name: platesnap
description: "PlateSnap - License Plate Scanner App for Vietnam"
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Camera
  camera: ^0.11.0+2

  # ML / OCR (ML Kit only - no custom model needed)
  google_mlkit_text_recognition: ^0.14.0

  # State Management
  provider: ^6.1.2

  # Local Storage
  sqflite: ^2.4.1
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5

  # UI
  flutter_svg: ^2.0.16

  # Utils
  permission_handler: ^11.3.1
  intl: ^0.20.1
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  vibration: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
